# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb96e5f3f89049c1ab3affa8d017961c8f701b777929226ec5d35529ea46c4a524cb03aa8b7584919b47529c710cdcc69efce8396b719f565ffd42cecf54116c

test:
  secret_key_base: f90f871e7a2033b88b38884d7abc0e12c89065efc9ffcf280ea38ef3cf82b20cce6863e9808c6aa9820beb0e33b197e0cf31bc226b64d1b454c77ac81889bf3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
